# Simple Covariance Matrix

In [20]:
# Import Library

import numpy as np
import pandas as pd


In [21]:

# Simple data

d = {
    "Estudante": [1, 2, 3, 4, 5],
    "GAAL": [90, 65, 40, 80, 60],
    "PDS1": [80, 75, 90, 60, 100],
    "Cálculo 1": [60, 90, 60, 59, 80],
    "ALC": [95, 70, 55, 75, 80]
    }

data = pd.DataFrame(d); data

Estudante  GAAL  PDS1  Cálculo 1  ALC
0          1    90    80         60   95
1          2    65    75         90   70
2          3    40    90         60   55
3          4    80    60         59   75
4          5    60   100         80   80

In [22]:

arr = np.array(data[['GAAL','PDS1','Cálculo 1', "ALC"]]); arr

array([[ 90,  80,  60,  95],
       [ 65,  75,  90,  70],
       [ 40,  90,  60,  55],
       [ 80,  60,  59,  75],
       [ 60, 100,  80,  80]])

In [45]:
mat_cov = np.cov(arr.T, bias=True); mat_cov # Veja [1],[3], np.cov(MATRIX), MATRIX rows represent features.

array([[ 296.  , -132.  ,  -42.6 ,  195.  ],
       [-132.  ,  184.  ,   44.2 ,  -15.  ],
       [ -42.6 ,   44.2 ,  164.16,  -10.  ],
       [ 195.  ,  -15.  ,  -10.  ,  170.  ]])

- Observe que a diagonal representa a variancia de cada feature.

In [62]:
# Realizando os cálculos de forma manual

#Veja [2]
def calcula_matrizCovariancia(X):
    matCov = np.array([])
    numCols = X.shape[1]
    
    for i in range(numCols):
        for j in range(numCols):
            Y = np.mean( (X[:,i] - np.mean(X[:,i])) * (X[:,j] - np.mean(X[:,j])).T )
            matCov = np.append(matCov, Y)
    
    return matCov.reshape(-1,numCols)


In [63]:
calcula_matrizCovariancia(arr)

array([[ 296.  , -132.  ,  -42.6 ,  195.  ],
       [-132.  ,  184.  ,   44.2 ,  -15.  ],
       [ -42.6 ,   44.2 ,  164.16,  -10.  ],
       [ 195.  ,  -15.  ,  -10.  ,  170.  ]])

## Reference

[1]https://numpy.org/doc/stable/reference/generated/numpy.cov.html<br>
[2]https://en.wikipedia.org/wiki/Covariance_matrix<br>
[3]https://stackoverflow.com/questions/15317822/calculating-covariance-with-python-and-numpy<br>