In [11]:

import numpy as np
import scipy

A = np.array([-1.51, 0.93, -1.15, -1.29, -1.49,1.15,-0.22,2.43,1.15]).reshape(3,3)

A

array([[-1.51,  0.93, -1.15],
       [-1.29, -1.49,  1.15],
       [-0.22,  2.43,  1.15]])

In [2]:

np.linalg.det(A)

11.93332

In [3]:

A.T

array([[-1.51, -1.29, -0.22],
       [ 0.93, -1.49,  2.43],
       [-1.15,  1.15,  1.15]])

In [4]:

np.linalg.inv(A)

array([[-0.37776579, -0.32379924, -0.05396654],
       [ 0.10311464, -0.16671806,  0.2698327 ],
       [-0.29015396,  0.29033831,  0.28907295]])

In [7]:
B = np.linalg.qr(A)

B

(array([[-0.75569935,  0.30805619, -0.57794453],
        [-0.64559745, -0.49875791,  0.57831174],
        [-0.11010189,  0.81014932,  0.57579132]]),
 array([[ 1.99814914e+00, -8.40778080e-03,  2.22044605e-16],
        [ 0.00000000e+00,  2.99830441e+00,  3.83550115e-03],
        [ 0.00000000e+00,  0.00000000e+00,  1.99185474e+00]]))

In [8]:
C = B[0]

In [9]:
np.linalg.inv(C)

array([[-0.75569935, -0.64559745, -0.11010189],
       [ 0.30805619, -0.49875791,  0.81014932],
       [-0.57794453,  0.57831174,  0.57579132]])

In [10]:
C.T

array([[-0.75569935, -0.64559745, -0.11010189],
       [ 0.30805619, -0.49875791,  0.81014932],
       [-0.57794453,  0.57831174,  0.57579132]])

In [14]:


import numpy as np

A = np.array([0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0]).reshape(4,4)


def matrizDeTransicao(M, alpha):
    vDiag = []
    n = len(M)
    
    for line in M:
        vDiag.append(sum(line))
        D = np.diag(vDiag)

    D_inv = np.linalg.inv(D)
    
    P = np.matmul(alpha*D_inv,M) + ((1-alpha)/n)*(np.ones((n,n)).T)
    return P


def matrizDeTransicao(M):
    matTransicao = np.array([])
    
    for line in M:
        sumLine = sum(line)
        matTransicao = np.append(matTransicao, line/sumLine)
    
    matTransicao = matTransicao.reshape(-1,len(M))
    return matTransicao

P_2 = matrizDeTransicao(A, 0.6);


# Display out

#P_2
print(P_2, end='\n\n\n')



LinAlgError: Singular matrix