# Basics TensorFlow

In [1]:

#Libraries
import numpy as np
import tensorflow as tf; # print(tf.version)

In [7]:

# Creating Tensors

s = tf.Variable("this is a string", tf.string)
n = tf.Variable(12, tf.int16)
n0 = tf.Variable(2, tf.int16)
f = tf.Variable(3.14, tf.float64)


In [9]:
print(s)
print(n)
print(n+n0)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=12>
tf.Tensor(14, shape=(), dtype=int32)


In [10]:

v = tf.Variable([[1,2,3,4]], tf.int32)

In [20]:
print(type(v))
print(v.shape)
v0 = np.array(v)
print(type(v0))
print(v0)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(1, 4)
<class 'numpy.ndarray'>
<tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>


In [23]:

t = tf.reshape(v, [2,2])
print(t)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [30]:

mat = [[1,2],[2,4],[4,5],[5,6]]

t = tf.Variable(mat, tf.int32)
print(t.shape)
print(type(t))
print(tf.rank(t))
print(t)

(4, 2)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
tf.Tensor(2, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(4, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 4],
       [4, 5],
       [5, 6]], dtype=int32)>


In [34]:
print(t[0,1])
print(t[0,:])
print(t[:,0])

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2 4 5], shape=(4,), dtype=int32)


## References

[1]https://colab.research.google.com/drive/1F_EWVKa8rbMXi3_fG0w7AtcscFq7Hi7B#forceEdit=true&sandboxMode=true&scrollTo=wVDmLJeFs086<br>
[2]https://www.youtube.com/watch?v=tPYj3fFJGjk<br>
